export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_DETAILS="GET_DETAILS";